version: '3'

services:
  # decrypter:
  #   build:
  #     context: ./
  #     dockerfile: ./Dockerfile
  #   container_name: decrypter
  #   command: npm run start
  #   volumes:
  #     - ./src:/root/server/src:rw
  chromakey:
    build:
      context: ./chromakey
      dockerfile: ./Dockerfile
    container_name: chromakey
    command: npm run start
    volumes:
      - ./chromakey/src:/root/chromakey/src:rw
